{{- if .Values.service.ratelimit.createGlobalConfig -}}
---
apiVersion: enroute.saaras.io/v1
kind: GlobalConfig
metadata:
  labels:
    app: {{ .Values.service.name }}-app
  name: {{ .Values.service.name }}-rl-global-config
  namespace: {{ .Release.Namespace }}
spec:
  name: {{ .Values.service.name }}-rl-global-config
  type: globalconfig_ratelimit
# for every xff, with proto https for default_route, enforce 2rps
# enroute_x-forwarded-for_10.0.20.90_x-forwarded-proto_https_generic_key_default_route_1617919413
  config: |
        {
          "domain": "enroute",
          "descriptors" :
          [
            {
              "key": "x-forwarded-for",
              "descriptors" :
              [
                {
                  "key" : "x-forwarded-proto",
                  "value" : "http",
                  "descriptors" : [
                   {
                     "key" : "generic_key",
                     "value" : "default_route",
                     "rate_limit" : { "unit" : "second", "requests_per_unit" : 5 }
                    }
                  ]
                },
                {
                  "key" : "x-forwarded-proto",
                  "value" : "https",
                  "descriptors" : [
                   {
                     "key" : "generic_key",
                     "value" : "default_route",
                     "rate_limit" : { "unit" : "second", "requests_per_unit" : 2 }
                   }
                  ]
                }
              ]
            }
          ]
        }
{{- end -}}

